### PR TITLE
updating trello and github repo links

### PR DESCRIPTION
**Pull request by gabegreenberg**
changed to:

https://trello.com/b/dwPR0LTz/vulcanjs-roadmap
https://github.com/VulcanJS/Vulcan

### CODE REVIEW

**Comment by SachaG** [comment]
Thanks but it'd be better to change it in the source file? https://github.com/VulcanJS/vulcan-home/blob/master/pages/index.js

**Comment by gabegreenberg** [comment]
agreed @SachaG and I already did. but it wasn't pushed to production. the site still has the old link.

**Comment by SachaG** [comment]
Oh you're right, sorry. I haven't worked on this repo in a while, I probably need to set up automatic deploys of some kind.

**Comment by gabegreenberg** [comment]
@SachaG 
I'd be happy to setup the vulcan home page on our netlify account which does automatic deploys and previews... and give you admin access. that's what we use for reactiflux! or you can setup the free version here: https://www.netlify.com/pricing/

**Pull request closed without merging**
